$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:2
        },
        400:{
            items:3
        },
        600:{
            items:4
        },
        950:{
            items:6
        }
    }
})